### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by jtagcat**
Ignore files created by end users,
and not published by developers.

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
Sounds good.

On that topic, would you think it makes sense to ignore all the other folders except the three that exist right now?

**Comment by jtagcat** [comment]
Not really, what for? If you'd have other chrome hacks, you'd have this in a subfolder, not the other way around.

**Comment by MrOtherGuy** [comment]
>  If you'd have other chrome hacks, you'd have this in a subfolder, not the other way around.

I see what you mean, but would you really? I'm really hesitant to go and assume that. I could easily imagine that one clones this repo as their chrome folder (in which case your proposed gitignore certainly makes sense) and then builds up their own setup from that, possibly by adding an "images" folder for custom icons etc.

Nonetheless, I can merge this one and think about the further additions afterwards.

**Comment by jtagcat** [comment]
You can always do `mv chrome chrome.tmp; mkdir chrome; mv chrome.tmp chrome/csshacks; mv chrome/csshacks/user{Chrome,Content}.css chrome`, then use your preferred editor to prepend `csshacks` to all paths in the `user{Chrome,Content}.css` files.

It's easy to do. Unlike https://github.com/overdodactyl/ShadowFox, https://github.com/MrOtherGuy/firefox-csshacks doesn't rely on monopoly of the chrome folder.

**Comment by MrOtherGuy** [comment]
Hmm yeah, maybe you are right.

Anyway, thanks for this,

**Pull request merged**
