### PR TITLE
Adding caption hacks!

### PR DESCRIPTION
**Pull request by Ryan-da-ghost**

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
Thanks for effort, but I'm not going to merge these in current state.

Please answer some questions so and I'll consider it:

1. Why do you you set color variables as three separate numbers? Setting them directly to rgba(x,y,x) is clearer. It's fine though if you have some good reason for it.
2. What is the purpose of lines 9-13 setting buttonbox to relative and having negative top margin? Is it just to move the buttonbox a bit higher? Doesn't that make look super inconsistent since the buttons are not center aligned anymore? Also, it moves them way too high if you have menubar enabled and breaks compatibility with some other stylesheets in this repository. I would rather remove that ruleset completely.
3. `--third-accent-color` doesn't exist anywhere, so hovering the buttons makes them invisible.
4. You should prefix variables that are not used by Firefox itself by `--uc-` so it's clear that this is custom variable.
5. Do not set fixed color background for the buttonbox. The style should work with whatever theme the user has (when reasonable) and fixed color prevents that. You can use `transparent` here instead.
6. The lines at the end don't do anything and should be removed. 

Additionally, the only functional difference I can see with the two stylesheets is the color of the buttons. I don't want to have two separate files just for that. There's some better options, like making either one the default and then have a commented-out set of rules to set a color variable. Then the icon would fall back to default if the variables don't exist. Or you could invent a pref that the user could set. Nonetheless, I think the "grey" color should probably be inherited from whatever icon color the toolbar uses, not fixed grey.

Also, I would like to add the default license-block to the top of this file if it's okay for you. It's not so much about the license itself, but it informs the user where that part of their userChrome.css came from as well as serves as nice way to create a "section" in their file. I mean, I'm pretty confident that most users don't use git, nor use `@import` but instead just mash some css directly into their userChrome.css.

**Comment by MrOtherGuy** [comment]
Additionally, the file should probably be called `round_caption_button.css` because it doesn't really have anything to do with dark mode nor is it mac specific.

**Comment by MrOtherGuy** [comment]
Hey man, I didn't mean I don't want this style added. Just not in its current state.

If you want, I can make a style that does visually the same thing in a manner that I will accept (actually I have a version already). Or you can work on it if you wish to. I would add the negative top margin as optional, and do it in a manner that works with Proton (so it probably requires a small change in non-proton styling). The color would be default "colorful", but you could go into about:config and set `ui.userchrome.colorful-captions-disabled` to make them "greyscale" or whatever color your toolbar icons use.

**Comment by Ryan-da-ghost** [comment]
If you have a working version feel free to publish it, I couldn't care any less. Felt like doing some pulls and stumbled upon this. When you have a working version why would you need me? after all you don't prefer my coding style.... I updated it to where you wanted, what you want isn't what everyone wants.... I don't want to get into this really long convo so we might as well never talk again. That should fix everything.

Stay safe
Ryan.

**Comment by MrOtherGuy** [comment]
As you wish. I'm just saying that you were the one who decided to close the pull request on your own after I had merely requested some changes or at least answers to some questions.

It's not about if I need your code or not, I just wanted to give you a chance to finish your contribution instead of just "taking your idea" and moving on while dismissing your effort. But if you don't want to modify to fit this repo then cool, don't - I'm not going to force you to do anything, but I gave you a chance.

Anyhow, no hard feelings - and stay safe.

**Comment by Ryan-da-ghost** [comment]
let me do a recap : 

     Why do you you set color variables as three separate numbers? Setting them directly to rgba(x,y,x) is clearer. It's fine though if you have some good reason for it.
I fixed this.

     What is the purpose of lines 9-13 setting buttonbox to relative and having negative top margin? Is it just to move the buttonbox a bit higher? Doesn't that make look super inconsistent since the buttons are not center aligned anymore? Also, it moves them way too high if you have menubar enabled and breaks compatibility with some other stylesheets in this repository. I would rather remove that ruleset completely.
I removed the ruleset

     --third-accent-color doesn't exist anywhere, so hovering the buttons makes them invisible.
I added third accent color

     You should prefix variables that are not used by Firefox itself by --uc- so it's clear that this is custom variable.
This is why i closed my pull
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/auto_devtools_theme_for_rdm.css 
Looking at this you never added --uc- I would add it , but how much of a diff would it make?!

    Do not set fixed color background for the buttonbox. The style should work with whatever theme the user has (when reasonable) and fixed color prevents that. You can use transparent here instead.
No, i never made this so it would have `blue green yellow` , `blue darkblue skyblue`, `pink purple blue`. I made it `green red yellow`, and `gray dark-grady darker-gray`

    The lines at the end don't do anything and should be removed.
removed.

**Comment by MrOtherGuy** [comment]
> This is why i closed my pull
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/auto_devtools_theme_for_rdm.css
Looking at this you never added --uc- I would add it , but how much of a diff would it make?!

That's precisely why I would want you to add them. --uc- prefix should NOT be used in that file because we are *modifying* value of variables that **already exist**. But you should prefix variables that you are "inventing" yourself for the very purpose of distinguishing between the two cases. Doing so tells the user that Firefox's own style doesn't depend on a value of any --uc- prefixed variables. Ideally, if you see a variable used in this repo and it doesn't have --uc- prefix then you'll know it's something that originates from and/or is used by Firefox internal styles.


> No, i never made this so it would have blue green yellow , blue darkblue skyblue, pink purple blue. I made it green red yellow, and gray dark-grady darker-gray

Honestly I don't understand what you mean by this. But [see line 9](https://github.com/MrOtherGuy/firefox-csshacks/pull/100/commits/d3453a25ca5cfead4de533d8da1e386d5cf1157c#L9https://github.com/MrOtherGuy/firefox-csshacks/pull/100/commits/d3453a25ca5cfead4de533d8da1e386d5cf1157c). There, you are making the background of the buttons (sure, I was wrong - not the buttonbox) use the opaque color of `var(--dark-color)`. Yes, the icons would be round, but the clickable area of the buttons would have a opaque dark background, which appears to only match default dark theme background of Firefox 87. For example, it would  not match Proton styling that has different color. Nor does it match installable theme. 

Look, the suggestions/requirements are to make the styles better by making them more generally usable and be less dependent on the users exact environment. It's not about if I personally prefer some look over another  - I mean, I'm not going to use this particular style anyway, much like I don't use the majority of other styles in the repo. But I want the styles that exist to have some "quality" and I feel it's more fair to let the people who decide to contribute make their work good by giving suggestions of what I think would achieve that goal.

Of course one can give arguments to convince me that what they are doing is for the better because there are certainly scenarios that I have not thought about.

**Comment by Ryan-da-ghost** [comment]
Let's just end this here.

**Comment by rediffusion** [comment]
Hi, Y'all! 👋

 Is this for a theme, right? What do they look like?
`chrome/auto_devtools_theme_for_rdm.css`
`content/auto_devtools_theme.css`
Do you have the screens?

**Comment by MrOtherGuy** [comment]
They are for styling developer tools based on your dark theme preference, but are quite unnecessary nowadays since devtools have such a feature built-in.

**Pull request closed without merging**
