### PR TITLE
Allowing disable 'hover' or 'focus' behavior via properties

### PR DESCRIPTION
**Pull request by Neil561**

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
Would you explain what this would achieve or improve? I'm not completely against this, but I kinda feel it creates more complexity without any obvious benefits.

**Comment by Neil561** [comment]
Sorry I didn't explain it better (or at all 😅).

The idea is to be capable of disable the 'hover' or 'focus' behavior from the userChrome.css, without having to modify autohide_bookmarks_toolbar.css by commenting out the undesired options. 

For example, using this, my userChrome.css disabling 'hover' looks like this:

```css
@import url("firefox-csshacks/chrome/autohide_bookmarks_toolbar.css");

#PersonalToolbar{
  --uc-autohide-toolbar-transform-hover: var(--uc-autohide-toolbar-transform-hide);
}
```

**Comment by MrOtherGuy** [comment]
I see. But I can't help but to think that it be more clear to set the transform value directly in userChrome.css like:

```css
@import url("firefox-csshacks/chrome/autohide_bookmarks_toolbar.css");

#navigator-toolbox:hover > #PersonalToolbar{ transform: rotateX(90deg) }
```

In any event, I feel the variables `*-show: rotateX(0)` and `*-hide: rotatex(90deg)` are quite unnecessary.

**Comment by Neil561** [comment]
Good point.

There is just a little detail: the code you just put it's not quite enough since it's going to hide the toolbar on hover even when the 'awesomebar' has the focus. I'm not sure if it's because the hover rule is after the focus one or if the selector has a higher value. That's why I had to include this too in autohide_bookmarks_toolbar.css:

```css
#navigator-toolbox:hover > #nav-bar:focus-within + #PersonalToolbar {
  transition-delay: 100ms !important;
  transform: var(--uc-autohide-toolbar-transform-show);
}
```

You are right, the variables *-show and *-hide are not necessary; it's highly improvable that the show and hide transform will need to be changed; it's the only case I can think those variable can be quite useful.

In any case, thanks again for a great project.

**Comment by MrOtherGuy** [comment]
> ..because the hover rule is after the focus one or if the selector has a higher value. That's why I had to include this too

Yeah, indeed that unfortunate. Thing is, I don't really want to make things more complicated than they need to be so I'm a bit hesitant to do merge this.

But at first glance it seems fine if you make a change to the pull request to remove the *-show and *-hide variables. Then in userChrome.css you could just use:

```css
#PersonalToolbar{ --uc-autohide-toolbar-transform-hover: transform(90deg) }
```

And it would work correctly because of the last ruleset you mentioned in your previous comment. 

Also, I think the variable name is not very good, but at the moment I'm not sure what a correct one would be.

**Comment by Neil561** [comment]
I understand; the variables are gone now.

**Comment by MrOtherGuy** [comment]
Sorry, I didn't mean for you to remove *all* the variables, but just the *-show and *-hide ones.

So you would have these two (I think these are better names too):

```css
  --uc-autohide-toolbar-focus-rotation: 0deg;
  --uc-autohide-toolbar-hover-rotation: 0deg;
```

Then use them like so:

```css
#nav-bar:focus-within + #PersonalToolbar{
  transition-delay: 100ms !important;
  transform: rotateX(var(--uc-autohide-toolbar-focus-rotation,0));
}
```
And then indeed this last bit (note that transition delay is unnecessary here since it's being added by either or both above):

```css
#navigator-toolbox:hover > #nav-bar:focus-within + #PersonalToolbar { transform: rotateX(0) }
```

Right? Afterwards you can just use `#PersonalToolbar{ --uc-autohide-toolbar-focus-rotation: 90deg }` in userChrome.css and it will only set the transform for focus state.

Make these changes and I'll merge it. I think the correct place for comment on how to use variables is atop of the file where they are defined - something like this:

```css
  --uc-autohide-toolbar-delay: 600ms; /* The toolbar is hidden after 0.6s */

  /* 0deg = "show" ; 90deg = "hide"  */
  --uc-autohide-toolbar-focus-rotation: 0deg;
  --uc-autohide-toolbar-hover-rotation: 0deg;
```

Note that most folks copy content straight to userChrome instead of importing (sadly) so mentioning userChrome as a file might be confusing.

Also, you should delete some old comments since now one should modify these variables to set desired behavior instead of deleting code blocks. But really, I can fix comments later myself too.

**Comment by Neil561** [comment]
Perfect, check it now.

**Comment by MrOtherGuy** [comment]
Yup, this looks good now. Thanks!

**Comment by Neil561** [comment]
Thank you, I'm glad to help. If you don't mind I'm going to check the open issues.

**Pull request merged**
